#! @Chapter Utility Functions
#! @Section Maximal Subgroups
#! @Arguments n, p, e, f
#! @Description
#! Return the subgroup of <M>SL(n, p ^ e)</M> induced by the subgroup of
#! <M>GL(n, p ^ e)</M> generated by <M>GL(n, p ^ f)</M> and the center
#! <M>Z(GL(n, p ^ e))</M> (i.e. all scalar matrices), where <C>GF(p ^ f)</C> is
#! a subfield of <C>GF(p ^ e)</C>. Note that this means <A>f</A> must be a
#! divisor of <A>e</A>. We further demand that <A>p</A> be a prime number and
#! that the quotient <C>f / e</C> be a prime number as well, i.e. <C>GF(p ^
#! e)</C> is a prime extension of <C>GF(p ^ f)</C>.
DeclareGlobalFunction("SubfieldSL");
